/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package belanja;

/**
 *
 * @author Martha
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jUsername1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jButton1_Login = new javax.swing.JButton();
        jButton2_Register = new javax.swing.JButton();
        jWarning = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("WELCOME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, 40));

        jLabel2.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        jLabel2.setText("Silahkan, masukkan username dan password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 340, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 80, 30));

        jUsername1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsername1ActionPerformed(evt);
            }
        });
        jPanel1.add(jUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 240, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Username :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 80, 30));
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 240, 30));

        jButton1_Login.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton1_Login.setText("Login");
        jButton1_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 90, 30));

        jButton2_Register.setText("Register");
        jButton2_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 110, 30));

        jWarning.setForeground(new java.awt.Color(255, 51, 51));
        jWarning.setToolTipText("");
        jPanel1.add(jWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 230, 20));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 500, 390);

        jPanel2.setBackground(new java.awt.Color(240, 240, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel5.setText("TOKO FATAH JAYA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 220, 40));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsername1ActionPerformed

    private void jButton2_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_RegisterActionPerformed
           Register rg = new Register();
           rg.setVisible(true);
           rg.pack();
           rg.setLocationRelativeTo(null);
           rg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton2_RegisterActionPerformed

    private void jButton1_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_LoginActionPerformed
        if(jPassword.getText().equals(Register.password)&&(jUsername1.getText().equals(Register.username))) {  
        
           Menu mn = new Menu();
           mn.setVisible(true);
           mn.pack();
           mn.setLocationRelativeTo(null);
           mn.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
        }
        else{
            jWarning.setText("Your Password atau Username is invalid");
        }
    }//GEN-LAST:event_jButton1_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Login;
    private javax.swing.JButton jButton2_Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUsername1;
    private javax.swing.JLabel jWarning;
    // End of variables declaration//GEN-END:variables
}
